"""empty message

Revision ID: e651806014a1
Revises: 3ff12351fc7c
Create Date: 2020-10-10 11:56:37.738670

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e651806014a1'
down_revision = '3ff12351fc7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('HP', sa.String(), nullable=True))
    op.add_column('results', sa.Column('siege_weapon', sa.String(), nullable=True))
    op.drop_column('results', 'url')
    op.drop_column('results', 'result_all')
    op.drop_column('results', 'result_no_stop_words')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('result_no_stop_words', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('result_all', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('results', 'siege_weapon')
    op.drop_column('results', 'HP')
    # ### end Alembic commands ###
